config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "demo",      to: "welcome#demo",        as: :demo

  get "signup",    to: "admin/users#new",     as: :signup
  get "settings",  to: "admin/users#edit",    as: :settings

  get "signin",    to: "admin/auths#new",     as: :signin
  get "signout",   to: "admin/auths#destroy", as: :signout

  namespace :admin do

    resources :auths, only: [:new, :create, :destroy]
    resources :users, only: [:index, :new, :create, :update, :destroy]

    resources :events, param: :event_id

    scope 'events/:event_id', as: :event do
      get "/preview", to: "events#preview", as: :preview

      resources :venues, param: :venue_id
      scope 'venues/:venue_id', as: :venue do
        resources :locations, param: :location_id
      end

      resources :sessions, param: :session_id
      resources :participants, param: :participant_id
      resources :roles, param: :role_id
      resources :rsvps
      resources :participations

      resources :links, param: :link_id

      resources :videos, controller: "media"
      resources :audios, controller: "media"
      resources :photos, controller: "media"
    end
  end
end

app/models/audio.rb
class Audio < Medium
end

app/models/event.rb
class Event < ApplicationRecord

  has_permalink :create_slug

  has_many :links
  has_many :participants
  has_many :participations
  has_many :roles
  has_many :rsvps
  has_many :sessions
  has_many :sponsor_levels
  has_many :sponsors, through: :sponsor_levels
  has_many :venues
  has_many :locations, through: :venues

  has_many :media  # used by photos, audio, video
  has_many :audios # uses media
  has_many :photos # uses media
  has_many :videos # uses media

  belongs_to :user

  validates :name, presence: :true

  def create_slug
    "#{name} #{iterator} #{city} #{state}"
  end

end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :url, presence: true

  before_update :ensure_protocol
  before_create :ensure_protocol

  PROTOCOL_REGEX = /^https*:\/\//

  def name
    pieces = [ title ]

    if content.present?
      piece = content[0..50]
      if content.length > 50
        piece << "..."
      end
      pieces << piece
    end

    pieces << url.sub(PROTOCOL_REGEX, "")
    pieces.map{ |l| l unless l.blank? }.compact.first
  end

  def ensure_protocol
    unless self.url =~ PROTOCOL_REGEX
      self.url = "http://#{self.url}"
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :venue
  has_many :sessions
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :session

  def name
    [
      title,
      namify_url(image_url),
      namify_url(audio_url),
      namify_url(vimeo_url),
      namify_url(instagram_url),
      namify_url(flickr_url),
      namify_url(facebook_url),
      namify_url(soundcloud_url),
      namify_url(video_url),
      namify_url(youtube_url),
      namify_url(vine_url),
      id
    ].map{ |l| l unless l.blank? }.compact.first
  end

  def namify_url(url)
    if url.nil?
      nil
    else
      if url.split("/").last.nil?
        nil
      else
        url.split("/").last.split(".").first
      end
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
  has_many :participations
  has_many :sessions, through: :participations

  validates :name, presence: :true

  def role_for(session)
    Participation.find_by(session: session, participant: self).role.name
  end
end

app/models/photo.rb
class Photo < Medium
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :event
  has_many :participations

  validates :name, presence: :true
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :participant
  belongs_to :event

  validates :attending, presence: :true
  validates :participant_id, presence: :true

  def yes?
    attending == 1
  end

  def maybe?
    attending == 0
  end

  def no?
    attending == -1
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :event
  belongs_to :location

  has_many :participations
  has_many :participants, through: :participations

  has_many :media  # used by photos, audio, video
  has_many :audios # uses media
  has_many :photos # uses media
  has_many :videos # uses media

  accepts_nested_attributes_for :participations,
    reject_if: proc { |params| params['participant_id'].blank? || params['role_id'].blank? },
    allow_destroy: true

  accepts_nested_attributes_for :participants, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: :true

  scope :active, -> { joins(:participations).where("participations.participant_id IS NOT NULL")}

  def break?
    participants.empty?
  end

  def time_range
    "#{starts_at.strftime("%H:%M")} - #{ends_at.strftime("%H:%M")}"
  end
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  belongs_to :event
  belongs_to :sponsor_level
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: :true, on: :create
  validates :email,    presence: :true, uniqueness: true, on: [:create, :update]

  has_many :events
  has_many :venues
  has_many :participants
  has_many :sessions
  has_many :media
  has_many :photos
  has_many :audios
  has_many :videos
  has_many :links
  has_many :locations
end

app/models/venue.rb
class Venue < ApplicationRecord
  validates :name, presence: :true
  
  belongs_to :event
  has_many :locations
end

app/models/video.rb
class Video < Medium
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def link_to_social(site, username)
    if site == :bandcamp
      url = "https://#{username}.#{site}.com"
    else
      url = "https://#{site}.com/#{username}"
    end
    
    link_to username, url, class: "u-url", target: "_blank"
  end
  
  def human_readable_url(url)
    url.gsub(/^.*:\/\//, "").gsub(/^www\./, "").gsub(/\/$/, "")
  end
end

app/helpers/media_helper.rb
module MediaHelper
  def media_embeds_for_type(type)
    embeds = {
      audio: %w(audio soundcloud),
      video: %w(video instagram flickr facebook youtube vimeo vine),
      photo: %w(image instagram flickr facebook)
    }

    embeds[type.downcase.to_sym]
  end

  def creator_photo_tag(resource)
    if resource.creator_photo.present?
      image_tag resource.creator_photo, alt: "#{resource.creator_name}'s profile photo", class: "u-photo"
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
  def role_options_for_select(event, selected=nil)
    options_for_select event.roles.all.map{ |r| [r.name, r.id] }, selected
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_events.html.erb
<div id="events">
  <h2>
    Events
    <%= link_to "NEW", [:new, :admin, :event], class: "btn btn-primary btn-xs" %>
  </h2>

  <% if current_user.events.blank? %>
    <p>You haven&rsquo;t added any events yet.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.events.each do |event| %>
          <tr>
            <td><%= link_to event.name, [:admin, event] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/dashboard/_links.html.erb
<dl>
  <% event.links[0..3].each do |link| %>
    <dt><%= link_to link.name, [:admin, event, link] %></dt>
    <dd><%= link.content[0..200] %></dd>
  <% end %>
</dl>

app/views/dashboard/_locations.html.erb
<div id="locations">
  <h2>
    Locations
    <%= link_to "NEW", [:new, :admin, event, venue, :location], class: "btn btn-primary btn-xs" %>
  </h2>

  <% if venue.locations.blank? %>
    <p>You haven&rsquo;t added any locations yet.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>

      <tbody>
        <% venue.locations.each do |location| %>
          <tr>
            <td><%= link_to location.name, [:admin, event, venue, location] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/dashboard/_media.html.erb
<% event.send(section)[0..3].in_groups_of(4, nil).each do |row| %>
  <div class="row">
    <% row.each do |medium| %>

      <div class="col-xs-12 col-sm-3">
        <article class="h-entry">

          <% if medium.present? %>
            <%= render "admin/media/embed",  medium: medium %>

            <h1 class="h4">
              <%= link_to_unless_current medium.name, [:admin, @event, medium], class: "p-name" %>
            </h1>
          <% end %>

        </article>
      </div>

    <% end %>
  </div><!-- .row -->
<% end %>

app/views/dashboard/_more_items.html.erb
<% if collection.length > limit %>
  <p>
    <%= link_to collection_path do %>
      And <%= collection.length - limit %> more...
    <% end %>
  </p>
<% end %>

app/views/dashboard/_participants.html.erb
<dl>
  <% event.participants.order(:name).each do |participant| %>
    <dt><%= link_to participant.name, [:admin, event, participant] %></dt>

    <% if participant.sessions.present? %>
      <% participant.sessions.each do |session| %>
        <dd><%= link_to "#{session.location.name} / #{session.time_range}", [:admin, event, session] %></dd>
      <% end %>
    <% end %>

  <% end %>
</dl>

app/views/dashboard/_photos.html.erb
<%= link_to [:admin, event, medium] do %>
  <%= image_tag medium.image_url, alt: medium.name %>
<% end %>

app/views/dashboard/_roles.html.erb
<dl>
  <% event.roles.each do |role| %>
    <dt><%= link_to role.name, [:admin, event, role] %></dt>

    <% if role.description.present? %>
      <dd><%= simple_format role.description %></dd>
    <% end %>

  <% end %>
</dl>

app/views/dashboard/_rsvps.html.erb
<p>
  <b><%= pluralize event.rsvps.count, "RSVP" %></b>
</p>

<p class="rsvp-counts">
  <span class="yes">
    <b><%= event.rsvps.count %></b>
    YES
  </span>

  <span class="maybe">
    <b><%= event.rsvps.count %></b>
    MAYBE
  </span>

  <span class="no">
    <b><%= event.rsvps.count %></b>
    NO
  </span>
</p>

app/views/dashboard/_section.html.erb
<section id="<%= section %>" class="col-xs-12 col-sm-<%= columns %>">
  <div class="page-header">
    <h2><%= link_to section.to_s.pluralize.capitalize,[:admin, event, section], class: "p-name" %></h2>
    <p class="header-button"><%= link_to "NEW", [:new, :admin, event, section.to_s.singularize], class: "btn btn-default btn-xs" %></p>
  </div>

  <% if event.send(section).blank? %>
    <p>You haven&rsquo;t added any <%= section.to_s.pluralize %> yet.</p>
  <% else %>
    <% if %w(photos audios videos).include?(section.to_s) %>
      <%= render "dashboard/media", event: event, section: section %>
    <% else %>
      <%= render "dashboard/#{section}", event: event %>
    <% end %>

    <%#= render "dashboard/more_items", event: event, collection: event.send(section), collection_path: [:admin, event, section], limit: 4 %>
  <% end %>
</section>

app/views/dashboard/_sessions.html.erb
<dl>
  <% event.sessions.order(:starts_at).each do |session| %>
    <dt><%= link_to session.name, [:admin, event, session] %></dt>

    <% if session.participants.present? %>
      <% session.participants.each do |participant| %>
        <dd><%= link_to participant.name, [:admin, event, participant] %> (<%= participant.role_for(session) %>)</dd>
      <% end %>
    <% end %>

  <% end %>
</dl>

app/views/dashboard/_venues.html.erb
<dl>
  <% event.venues.each do |venue| %>
    <dt>
      <%= link_to venue.name, [:admin, event, venue] %>
    </dt>

    <% if venue.locations.present? %>
      <% venue.locations.each do |location| %>
        <dd><%= link_to location.name, [:admin, event, venue, location] %></dd>
      <% end %>
    <% end %>

  <% end %>
</dl>

app/views/shared/_breadcrumbs.html.erb
<%= link_to_unless_current "All Events", admin_events_path %>

<% if current_event %>
  / <%= link_to_unless_current current_event.name, admin_event_path(current_event) %>
<% end %>

<% if controller_name == "sessions" %>
  <% if params[:session_id].present? %>
  / <%= link_to "Sessions", admin_event_sessions_path %>
  <% else %>
  /  Sessions
  <% end %>
<% end %>

<% if controller_name == "participants" %>
  <% if params[:participant_id].present? %>
  / <%= link_to "Participants", admin_event_participants_path %>
  <% else %>
  /  Participants
  <% end %>
<% end %>

<% if controller_name == "venues" || controller_name == "locations" %>
  <% if params[:venue_id].present? %>
  / <%= link_to "Venues", admin_event_venues_path %>
    <% if params[:location_id].present? %>
      / <%= link_to @venue.name, admin_event_venue_path(@event, @venue) %>
    <% end %>
  <% else %>
  /  Venues
  <% end %>
<% end %>

<% if controller_name == "roles" %>
  <% if params[:role_id].present? %>
  / <%= link_to "Roles", admin_event_roles_path %>
  <% else %>
  /  Roles
  <% end %>
<% end %>

<% if controller_name == "links" %>
  <% if params[:link_id].present? %>
  / <%= link_to "Links", admin_event_links_path %>
  <% else %>
  /  Links
  <% end %>
<% end %>

app/views/shared/_creator_form.html.erb
<fieldset>
  <legend>Author</legend>

  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="form-group">
        <%= f.label :creator_name, "Name".html_safe %>
        <%= f.text_field :creator_name, class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="form-group">
        <%= f.label :creator_url, "URL".html_safe %>
        <%= f.text_field :creator_url, class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="form-group">
        <%= f.label :creator_photo, "Photo".html_safe %>
        <%= f.text_field :creator_photo, class: "form-control" %>
      </div>
    </div>
  </div>
</fieldset>

app/views/shared/_danger_zone.html.erb
<div class="panel panel-danger danger-zone">
  <div class="panel-heading">
    <h3 class="panel-title">Want to delete this <%= label %>?</h3>
  </div>
  <div class="panel-body">
    You can delete this <%= label %> at anytime.
    All of <%= label == "participant" ? "their" : "its" %> assoicated data will be immediately and permanently deleted.
    There is <b>NO UNDO</b>.
  </div>
  <div class="panel-footer actions">
    <%= link_to "Destroy", resource, method: :delete, data: { confirm: "Are you sure you're sure? There is NO UNDO." }, class: "btn btn-danger" %>
  </div>
</div>

app/views/shared/_date_select_row.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <%= select_year resource.send(attr).try(:year),
          { prompt: true, start_year: Date.today.year , end_year: Date.today.year - 50 },
          name:  "#{resource.class.to_s.downcase}[#{attr}(1i)]",
          id:    "#{resource.class.to_s.downcase}_#{attr}_1i",
          class: "form-control datetime-select" %>
  </div>
  <div class="col-xs-12 col-sm-4">
    <%= select_month resource.send(attr).try(:month),
          { prompt: true },
          name:  "#{resource.class.to_s.downcase}[#{attr}(2i)]",
          id:    "#{resource.class.to_s.downcase}_#{attr}_2i",
          class: "form-control datetime-select" %>
  </div>
  <div class="col-xs-12 col-sm-4">
    <%= select_day resource.send(attr).try(:day),
          { prompt: true },
          name:  "#{resource.class.to_s.downcase}[#{attr}(3i)]",
          id:    "#{resource.class.to_s.downcase}_#{attr}_3i",
          class: "form-control datetime-select" %>
  </div>
</div>

app/views/shared/_for_event.html.erb
<p>For <%= link_to event.name, [:admin, event] %></p>

app/views/shared/_form_actions.html.erb
<div class="actions">
  <%= link_to "Cancel", @previous %>
  <%= f.submit class: "btn btn-success btn-lg" %>
</div>

app/views/shared/_form_errors.html.erb
<% if resource.errors.any? %>
  <% resource.errors.full_messages.uniq.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>.
    </div>
  <% end %>
<% end %>

app/views/shared/_media_footer.html.erb
<% if resource.creator_name.present? || resource.creator_url.present? %>
  <p class="p-author h-card">
    <% if resource.creator_name.present? && resource.creator_url.present? %>
      By:
      <%= creator_photo_tag(resource) %>
      <%= link_to resource.creator_name, resource.creator_url, class: "u-url p-name" %>

    <% elsif resource.creator_name.present? && resource.creator_url.blank? %>
      By:
      <%= creator_photo_tag(resource) %>
      <span class="p-name"><%= resource.creator_name %></span>

    <% elsif resource.creator_name.blank? && resource.creator_url.present? %>
      From:
      <%= creator_photo_tag(resource) %>
      <%= link_to resource.creator_url, resource.creator_url, class: "u-url" %>
    <% end %>
  </p>
<% end %>

<% if resource.published_at.present? %>
  <p>On: <%= time_tag resource.published_at, resource.published_at.strftime("%Y-%m-%d"), class: "dt-published" %></p>
<% end %>

app/views/shared/_media_header.html.erb
<header class="page-header">
  <h1>
    <%= link_to_unless_current medium.to_s.pluralize.capitalize, [@event, medium.to_s.pluralize.downcase], class: "p-name" %>
  </h1>

  <p><%= link_to "NEW", [:new, @event, medium.downcase], class: "btn btn-primary btn-xs" %></p>
  <p>For <%= link_to @event.name, @event %></p>
</header>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#site-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <p class="navbar-brand">
      <% if signed_in? %>
        <%= render partial: "shared/breadcrumbs" %>
      <% else %>
        <%= link_to "Home", root_path %>
      <% end %>
      </p>
    </div>

    <div class="collapse navbar-collapse" id="site-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to "Settings", settings_path %></li>
          <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="alert alert-info" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

app/views/shared/_time_select_row.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <%= select_hour resource.send(attr).try(:year),
          { prompt: true },
          name:  "#{resource.class.to_s.downcase}[#{attr}(4i)]",
          id:    "#{resource.class.to_s.downcase}_#{attr}_4i",
          class: "form-control datetime-select" %>
  </div>
  <div class="col-xs-12 col-sm-6">
    <%= select_minute resource.send(attr).try(:month),
          { prompt: true },
          name:  "#{resource.class.to_s.downcase}[#{attr}(5i)]",
          id:    "#{resource.class.to_s.downcase}_#{attr}_5i",
          class: "form-control datetime-select" %>
  </div>
</div>